<%@ Page Title="FAQ" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="FAQ.aspx.cs" Inherits="WebApplication1.FAQ" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        <h1><%: Title %>.</h1>
        <h2>Frequently Asked Questions page.</h2>
    </hgroup>

    <article>
        <p>        
            The following information was adapted from<a id="A1" runat="server" href="https://en.bitcoin.it/wiki/FAQ" target="_blank">Wikipedia</a>:
        </p>
        
        <h3>
            What are bitcoins?
        </h3>
        
        <p>        
            Bitcoins are the unit of currency of the Bitcoin system. A commonly-used shorthand for this is "BTC" to refer to a price or amount (eg: "100 BTC") A Bitcoin isn't actually a 'thing' you can point at. It is just a number associated with a Bitcoin address. 
        </p>

        <h3>
            How are new Bitcoin created or mined?
        </h3>
        
        <p>        
            New coins are generated by a network node each time it finds the solution to a certain mathematical problem (i.e. creates or mines a new block), which is difficult to perform and can demonstrate a proof of work. The reward for solving a block is automatically adjusted so that in the first 4 years of the Bitcoin network, 10,500,000 BTC will be created. The amount is halved each 4 years, so it will be 5,250,000 over years 4-8, 2,625,000 over years 8-12 and so on. Thus the total number of coins will approach 21,000,000 BTC over time. <br /><br />
        </p>

        <p>
            In addition, built into the network is a system that attempts to allocate new coins in blocks about every 10 minutes, on average, somewhere on the network. As the number of people who attempt to generate these new coins changes, <a id="A3" runat="server" href="http://bitcoindifficulty.com" target="_blank">the difficulty</a> of creating new coins changes. This happens in a manner that is agreed upon by the network as a whole, based upon the time taken to generate the previous 2016 blocks. The difficulty is therefore related to the average computing resources devoted to generate these new coins over the time it took to create these previous blocks. The likelihood of somebody "discovering" one of these blocks is based on the computer they are using compared to all of the computers also generating blocks on the network. 
        </p>

        <h3>
            How divisible are Bitcoin?
        </h3>

        <p>
            Technically, a Bitcoin can be divided down to 8 decimals using existing data structures, so 0.00000001 BTC is the smallest amount currently possible. Discussions about and ideas for ways to provide for even smaller quantities of Bitcoins may be created in the future if the need for them ever arises. 
        </p>

        <h3>
            How long will it take to generate all the coins?
        </h3>

        <p>
            The last block that will generate coins will be block #6,929,999. This should be generated around year 2140. Then the total number of coins in circulation will remain static at 20,999,999.9769 BTC.  <br /><br />
        </p>
        
        <p>
            Even if the allowed precision is expanded from the current 8 decimals, the total BTC in circulation will always be slightly below 21 million (assuming everything else stays the same). For example, with 16 decimals of precision, the end total would be 20999999.999999999496 BTC. 
        </p>

        <h3>
            Why does my Bitcoin address keep changing?
        </h3>

        <p>
            Whenever the address listed in "Your address" receives a transaction, Bitcoin replaces it with a new address. This is meant to encourage you to use a new address for every transaction, which enhances anonymity. All of your old addresses are still viewable in your history. 
        </p>

        <h3>
            Where does the value of Bitcoin stem from? What backs up Bitcoin?
        </h3>

        <p>
            Bitcoins have value because they are accepted as payment by many. eg: Peer to Peer, as well as<a id="A2" runat="server" href="http://wordpress.com" target="_blank">Wordpress</a>, <a id="A4" runat="server" href="http://reddit.com" target="_blank">Reddit</a>, etc. <br /><br />
        </p>

        <p>
            When we say that a currency is backed up by gold, we mean that there's a promise in place that you can exchange the currency for gold. In a sense, you could say that Bitcoin is "backed up" by the price tags of merchants - a price tag is a promise to exchange goods for a specified amount of currency.  <br /><br />
        </p>

        <p>
            It's a common misconception that Bitcoins gain their value from the cost of electricity required to generate them. Cost doesn't equal value - hiring 1,000 men to shovel a big hole in the ground may be costly, but not valuable. Also, even though scarcity is a critical requirement for a useful currency, it alone doesn't make anything valuable. For example, your fingerprints are scarce, but that doesn't mean they have any exchange value. 
        </p>

        <h3>
            What if someone bought up all the existing Bitcoin?
        </h3>

        <p>
            What if somebody bought up all the gold in the world? Well, by attempting to buy it all, the buyer would just drive the prices up until he runs out of money. <br /><br />
        </p>
        
        <p>
            Not all Bitcoins are for sale. Just as with gold, no one can buy a Bitcoin that isn't available for sale. 
        </p>

    </article>

    <aside>
        <h3>Additional Information</h3>
        <p>        
            To learn more about Bitcoins:
        </p>
        <ul>
            <li><a id="A5" runat="server" href="~/Ticker.aspx">Market Data</a></li>
            <li><a id="A6" runat="server" href="~/About">About</a></li>
            <li><a id="A7" runat="server" href="~/Contact">Contact</a></li>
        </ul>
    </aside>

</asp:Content>